const Event = {
  CANVAS_READY: "CANVAS_READY",
  TEST: "TEST",
  /*
   * ACTION
   */
  TIME: "TIME",
  SIZES: "SIZES",
  TOUCHDOWN: "TOUCHDOWN",
  TOUCHUP: "TOUCHUP",
  TOUCHMOVE: "TOUCHMOVE",
  DRAGGING: "DRAGGING",
  WHEEL: "WHEEL",
  CLICK: "CLICK",
  PRESS_HOLD: "PRESS_HOLD",
  PRESS_HOLD_RESET: "PRESS_HOLD_RESET",

  /*
   * WAIT ACTION
   */
  WAITSTART: "WAITSTART",
  WAITEND: "WAITEND",
  /*
   * LOADER
   */
  LOADER_START: "LOADER_START",
  LOADER_PROGRESS: "LOADER_PROGRESS",
  LOADER_FINISH: "LOADER_FINISH",
  LOADER_ANIM_FINISH: "LOADER_ANIM_FINISH",
  /*
   * WAIT ACTION
   */
  PAGE_ROUTING: "PAGE_ROUTING",
  PAGE_TRANSI_HIDE: "PAGE_TRANSI_HIDE",
  PAGE_TRANSI_HIDECALLBACK: "PAGE_TRANSI_HIDECALLBACK",
  PAGE_TRANSI_SHOW: "PAGE_TRANSI_SHOW",
  PAGE_TRANSI_SHOWCALLBACK: "PAGE_TRANSI_SHOWCALLBACK",
  EMIT_ROUTER: "EMIT_ROUTER",
  /*
   * OVERLAY
   */
  OPEN_CINEMATIC: "OPEN_CINEMATIC",

  NAV_PROGRESS_LOADER: "NAV_PROGRESS_LOADER",
  NAV_PROGRESS_LOAD: "NAV_PROGRESS_LOAD",
  NAV_RESET_LOAD: "NAV_RESET_LOAD",
  NAV_RESET: "NAV_RESET",
  NAV_CLOSEBTN: "NAV_CLOSEBTN",
  NAV_ARROW: "NAV_ARROW",
  NAV_UPDATE_COUNTER_CURRENT: "NAV_UPDATE_COUNTER_CURRENT",
  NAV_UPDATE_COUNTER_SUMMARY: "NAV_UPDATE_COUNTER_SUMMARY",
  NAV_STEP: "NAV_STEP",
  NAV_CLOSELAYER: "NAV_CLOSELAYER",
  NAV_DELETE_EMIT: "NAV_DELETE_EMIT",
  NAV_ADD_EMIT: "NAV_ADD_EMIT",
  /*
   * HOME
   */
  CONTACT_TOGGLE: "CONTACT_TOGGLE",
  CONTACT_CLOSE: "CONTACT_CLOSE",

  HOME_ADD_LISTENERS: "HOME_ADD_LISTENERS",
  HOME_REMOVE_LISTENERS: "HOME_REMOVE_LISTENERS",
  FULLSCREENMODE: "FULLSCREENMODE",
  DEVICE_ORIENTATION: "DEVICE_ORIENTATION",
  DEVICE_MOTION: "DEVICE_MOTION",
  /*
   * PROJECT
   */

  PROJECT_CHANGE: "PROJECT_CHANGE",

  BACKGROUND_TRANSISTOR_START: "BACKGROUND_TRANSISTOR_START",
  BACKGROUND_TRANSISTOR_END: "BACKGROUND_TRANSISTOR_END",
  /*
   * ABOUT
   */
  CURSOR_TOGGLE_ARROW: "CURSOR_TOGGLE_ARROW",
  CURSOR_TOGGLE_BORDER: "CURSOR_TOGGLE_BORDER",
  CURSOR_TOGGLE_DRAGH: "CURSOR_TOGGLE_DRAGH",
  CURSOR_TOGGLE_DRAGV: "CURSOR_TOGGLE_DRAGV",
  CURSOR_TOGGLE_EYE:"CURSOR_TOGGLE_EYE",
  PROJECT_TOGGLE: "PROJECT_TOGGLE",

  MUSIC_HIDE: "MUSIC_HIDE",
  MUSIC_SHOW: "MUSIC_SHOW",

  WORK_SCROLL_UPDATE: "WORK_SCROLL_UPDATE",
  // ABOUT_CLOSE: "ABOUT_CLOSE",
  // ABOUT_AFTER_OPEN: "ABOUT_AFTER_OPEN",
  // ABOUT_AFTER_CLOSE: "ABOUT_AFTER_CLOSE",
};

export default Event;
